### PR TITLE
Header and arrowkeys

### PR DESCRIPTION
**Pull request by Waffleboy**
## Changes

1. Simple fix for all headers to link back to home page

2. Added document listener to handle arrow keys to control cards. Left it as an abstraction should we want to extend the other keys in the future to do shortcuts or what not.

## Discussion
The headers are duplicated across every page, seems like a solid use case for a templating engine like handlebars but i didnt go that route cause of the 'pure js' approach. To consider if this is a good option in the future as the pages increase for maintainability?

### CODE REVIEW

**Comment by Waffleboy** [comment]
For point 2 on "doesn't work for local development", possible to elaborate? I'm experiencing the classic "it works on my machine" haha

**Comment by mantariksh** [comment]
Really?? Lol mine literally redirects to the path `/`
Screenshot 2020-07-16 at 4 27 28 PM

**Comment by Waffleboy** [comment]
Wow that is weird, im using the standard `npm start` and it seems to work..? Anyway, fixed the changes. I abstracted the method to a function in utils as I felt it was cleaner, but downside is having to add utils.js to every page

**Comment by mantariksh** [comment]
> Wow that is weird, im using the standard npm start and it seems to work..

Whoops this is probably my bad because I was being lazy and just opening the html files LOL sorry!! Thank you for making sure the room IDs are preserved though!

**Comment by Waffleboy** [comment]
Thanks @mantariksh !! :)

**Pull request merged**
